### ISSUE TITLE
Skill issue - Use a requirements.txt file instead - SCRUB

### ISSUE THREAD

**Issue by Terristwj** [DerrickLJH/EmotionBasedMusicRecommender#1]
## Your method of `pip install <module>` **sucks**. 
1. It requires users to install one-by-one manually
2. It does not specify the version of the module

## 1. **Steps to produce:**
1. Create a `requirements.txt` file in the root directory
2. Add dependencies into the `requirements.txt` file
3. Call `pip install -r requirements.txt` to autonomously install all dependencies within the `requirements.txt` file

### 2. Example of `requirements.txt` content:
`argcomplete==1.10.3`
`beautifulsoup4==4.8.2`
`blinker==1.6.2`
`cachecontrol==0.13.1`
`cachetools==5.3.1`
`certifi==2023.5.7`
`cffi==1.15.1`

### When done correctly, withIn the CLI, type `pip install -r requirements.txt` to install all required dependencies.

# **~ Skill Issue**

**Comment by DerrickLJH** [comment]
Noted with Thanks! Thanos of MOOC certs.
